### ISSUE TITLE
Add properly configured .gitignore file

### ISSUE THREAD

**Issue by JohnKhandygo** [CrazyTosser/Politech#1]
В .gitignore файле описываются файлы и директории, которые необходимо исключить при работе с данным репоиторием в git. В число таких файлов, как правило, включают специфичные для пользователей файлы, что позволяет избежать конфликтов при конкурентной работе с репозиторием. В частности, сюда целесообразно отнести файлы, [генерируемые IDE](https://intellij-support.jetbrains.com/hc/en-us/articles/206544839-How-to-manage-projects-under-Version-Control-Systems), поскольку их формат и содержание может отличаться от версии к версии. Для генерации .gitignore в idea удобно использовать [.ignore плагин](https://plugins.jetbrains.com/plugin/7495--ignore).

**Comment by CrazyTosser** [comment]
Сгенерировал

**Comment by JohnKhandygo** [comment]
Сгенерировали, только кривой какой-то. Теперь при открытии Вашего проекта нет зависимостей на junit, что не позволяет гонять тесты.

**Comment by CrazyTosser** [comment]
Эх, может iml не надо выкидывать? (метод научного тыка рулит)

**Comment by JohnKhandygo** [comment]
Может быть. Только мотивируйте свое решение как-нибудь.

**Comment by CrazyTosser** [comment]
Нууу, я просто не вспомнил другие файлы содержащие ссылки на инфу сборки проекта и вообще ссылки на junit

**Comment by CrazyTosser** [comment]
gitignore, чтобы включался iml файл проекта, поправил. Попробуйте, по идее junit сейчас должен сразу подтянуться
