### ISSUE TITLE
Upgrade tests 2.0

### ISSUE THREAD

**Issue by JohnKhandygo** [CrazyTosser/Politech#10]
- [x] Нет теста, который проверяет, что папка поиска по умолчанию выбирается. 
- [x] Не обязательно тестировать сторонние бибилотеки. Обычно можно считать, что они работают достаточно хорошо, ведь их разработчики должны были протестировать свою разработку, вер? ;)
- [x] Вместо того, чтобы создавать сложною струтктуру файлов для тетсирования и держать ее внутри проекта, лучше воспользоваться специальным механизмом junit [`TemporaryDirectory`](https://junit.org/junit4/javadoc/4.12/org/junit/rules/TemporaryFolder.html) ([пример использования](https://examples.javacodegeeks.com/core-java/junit/junit-temporary-folder-example/)). Используя это правило вместе с [`@BeforeClass`](http://junit.sourceforge.net/javadoc/org/junit/Before.html), Вы можете легко создать произвольную структуру папок, которая автоматически очистится после выполнения тестов.

**Comment by JohnKhandygo** [comment]
Собственно, про тесты в другом issue написал. 
- [x] Основное: они не работают.
- [x] Cмешивать файлы исходного кода, написанные на разных языках программирования, очень плохо. Пишите либо все на java, либо все на kotlin.

**Comment by CrazyTosser** [comment]
А что мне делать? Изначально я тесты писал на kotlin. Junit не компилировал тестовый класс требуя чтобы зааннотированная переменная @Rule была public. На явную пропись public он не реагирует, от слова совсем. Может я конечно делал что-то не так

**Comment by JohnKhandygo** [comment]
Во-первых, есть такая замечательная штука --- google. Например, мне удалось найти следующее [решение](https://discuss.kotlinlang.org/t/how-can-i-use-rule/304/6). Во-вторых, можно было написать о своей пробелме мне.  

Раз такая проблема имела место быть, окей, оставляйте как есть, но имейте ввиду на будущее.
