### ISSUE TITLE
Use consistent code style/formatting

### ISSUE THREAD

**Issue by JohnKhandygo** [CrazyTosser/Politech#3]
В исходном коде программы встречаются разночтения стиля кодирования/форматирования.

Кроме того, у Вас встречаются отступления от стандартного стиля кодирования для Java (в частности именование методов классов). Если Вы хотите использовать нестандартный стиль кодирования, пожалуйста опишите его отдельно, например в wiki (можно найти готовые спецификации в интернете или набросать свою, можно также взять что-то готовое а основу и описать только изменения) к этому репозиторию, в противном случае я буду считать, что код должен соответствовать [google java style guide](https://google.github.io/styleguide/javaguide.html).

**Comment by CrazyTosser** [comment]
Вроде бы к общепринятому стилю привел

**Comment by JohnKhandygo** [comment]
Не привели. Даже, если отвлечься от google java style, то Ваш стиль кодирования все еще неконсистентный, например в https://github.com/CrazyTosser/Politech/blob/0ff1dd4dcf6ec785631cb41406032cea2de7c2ef/src/spbstu/binartree/Tree.java#L20 цикл с single body expression начинается с `{`, а в https://github.com/CrazyTosser/Politech/blob/0ff1dd4dcf6ec785631cb41406032cea2de7c2ef/src/spbstu/binartree/Tree.java#L66 
нет.

**Comment by CrazyTosser** [comment]
Вроде подпричесал...
