### ISSUE TITLE
Upgrade Tree API 

### ISSUE THREAD

**Issue by JohnKhandygo** [CrazyTosser/Politech#4]
- [x] Ваша реализация не будет корректно работать в случае, если кто-то захочет использовать как библиотеку, из-за видимости некоторых полей. В общем считается хорошей практикой использовать наиболее жесткие возможные ограничения видимости. 
- [x] Метод https://github.com/CrazyTosser/Politech/blob/21114c5f313b2d514b08e8988855739f388a933e/src/spbstu/binartree/Tree.java#L120  неудобен для использования из-за числового аргумента `mode`: приходится постоянно подглядывать в реализацию для того, чтобы понять, какой `mode` необходим. Для решения этой проблемы можно либо заменить тип `mode` на какой-нибудь `enum` , элементы которого имеют говорящие названия, либо завести отдельные функции с говорящими названиями для каждого возможного значения `mode`.
- [x] Метод https://github.com/CrazyTosser/Politech/blob/21114c5f313b2d514b08e8988855739f388a933e/src/spbstu/binartree/Tree.java#L120 может вернуть `null`, что не очень удобно для сторонних пользователей. В общем считается, что не стоит использовать `null` как значение, обозначающее отсутствие чего-либо. Вместо этого лучше использовать `Optional` или завести специальное значение `Node`, обозначающее отсутствующий узел, но с которым можно работать так же, как и с любым другим значением `Node`.
- [x] Методы https://github.com/CrazyTosser/Politech/blob/21114c5f313b2d514b08e8988855739f388a933e/src/spbstu/binartree/Tree.java#L96 и 
https://github.com/CrazyTosser/Politech/blob/21114c5f313b2d514b08e8988855739f388a933e/src/spbstu/binartree/Tree.java#L106 не позволяют однозначно восстановить структуру дерева, что делает все Ваши тесты почти бессмысленными.

**Comment by CrazyTosser** [comment]
Вроде бы все замечания учел

**Comment by JohnKhandygo** [comment]
- [x] Первое замечание не исправлено. С одной стороны, Вы убрали метод, который "выставляет" наружу `Node`, но тогда видимость полей и методов класса `Node` слишком слабая. С другой стороны, метод, который Вы убрали (`getNode`) был необходим по условию задачи и Вы ничем его не заменили.
- [x] Собственно, согласно условию задачи, в Вашей реализации должны быть методы поиска числа в дереве и определения его соседей в дереве (предок, левый потомок, правый потомок). Я в Вашем коде не вижу ничего, что должно обеспечивать подобную функциональность.
- [x] Так и не понял, зачем Вы превратили свой код в помойку, перегрузив его таким количеством `Optional`'ов. То, что я писал про работу с `null`'ами (и `Optional`'ами в частности) касалось того, насколько удобно было бы пользоваться Вашей разработкой как библиотекой с точки зрения стороннего пользователя. Инкапсулированный код может (и, вероятно, должен) быть написан наиболее удобоваримо... Сейчас очень сложно разобраться, что же Вы делаете в `remove`, например. 
- [x] Метод https://github.com/CrazyTosser/Politech/blob/0ff1dd4dcf6ec785631cb41406032cea2de7c2ef/src/spbstu/binartree/Tree.java#L19 не учитывает возможность работы с `null`.

**Comment by CrazyTosser** [comment]
Кажется все исправил... И помойку вроде бы разгреб... Хотя уже не уверен

**Comment by JohnKhandygo** [comment]
- Первое замечание не исправлено. Вы легко можете это проверить, например, переместив свои тесты в любой другой пакет внутри проекта.
- Вы бросаете исключение в случае, когда не можете найти нужный узел. Это действительно настолько исключительная ситуация? 
- В коде не должно быть несодержательных комментариев. То есть по сути не должно быть комментариев, кроме Javadoc.
