### ISSUE TITLE
Upgrade tests

### ISSUE THREAD

**Issue by JohnKhandygo** [CrazyTosser/Politech#5]
- [x] Не весь код покрыт тестами (используйте Run test with Coverage для получения отчета по покрытию кода тестами). Не все варианты использования предусмотрены (имеется ввиду, что есть ситуации, в которых Ваша реализация ведет себя некорреткно). 
- [x] Методы https://github.com/CrazyTosser/Politech/blob/21114c5f313b2d514b08e8988855739f388a933e/src/spbstu/binartree/TreeTest.java#L48 и https://github.com/CrazyTosser/Politech/blob/21114c5f313b2d514b08e8988855739f388a933e/src/spbstu/binartree/TreeTest.java#L57
почти идентичны.

**Comment by CrazyTosser** [comment]
Вроде бы все варианты учел. Сейчас тесты покрывают все методы

**Comment by JohnKhandygo** [comment]
Не все покрыто. Вы можете посмотреть на покрытие следующим образом:
  1. Правый щелчок на классе (или пакете) с тестами в дереве проекта и выбрать `Run with Coverage`. 
  2. После прогона тестов будет выведена краткая статистика и, к тому же, все файлы исходного кода будут размечены (на полях слева) в соответствии с тем, затрагивали ли тесты ту или иную часть исходного кода

От Вас, естественно, не требуется покрывать тестами `equals`, `hashCode` и `toString`, но все значимые места должны быть протестированы.

**Comment by CrazyTosser** [comment]
Теперь дошло. Думал хватит 100% у методов ^^'
Довел до 99%. Почему Coverage считает эту строчку значимой и выделяет как непокрытую.
https://github.com/CrazyTosser/Politech/blob/789b1f95984cf2cd6739b4bfcc247856625d6e10/src/spbstu/binartree/Tree.java#L57

**Comment by JohnKhandygo** [comment]
Он просто считает ее непокрытой. Почему не знаю) С такими мелочами можно не пороться.
