### ISSUE TITLE
Upgrade impl. 2.0

### ISSUE THREAD

**Issue by JohnKhandygo** [CrazyTosser/Politech#9]
- [x] Уберите ненужные файлы из проекта. Ну серьезно, сколько раз надо повторять?
- [x] Если значение переменной/поля не меняется, лучше использовать `val`, а не `var`.
- [x] Зачем `program` на уровне класса объявлять? Я бы понял, если Вы его переиспользовать собираетесь, но так нет же, Вы его внутри метода инициализируете и используете один раз.
- [x] Секцию `init` лучше писать в самом начала объявления класса. А то я сидел, ломал голову, как это у Вас вообще работает, пока не увидел его где-то в самом низу.
- [x] Какой-то бред вытворяете при парсинге командной строки. Библиотека позволяет получить всю необходимую информацию из командной строки. RTFM, как говорится.
- [x] В `Cli::parse` Вы бросаете исключение для того, чтобы потом его самому же и поймать. Серьезно? 
- [x] Вы не правильно выбираете путь, в котором по умолчанию должен происходить поиск. В `user.dir` хранится путь, из которого был запущен java процесс. То есть, если я буду дергать Вашу программу из скрипта, не напрямую, то ничего не получится. 
- [x] Не понял, зачем держите в `Program` два метода, если один сводится к вызову второго? 
- [x] Вместо того, чтобы использовать `File::listFiles`, лучше воспользовать extension из kotlin [`File::walk`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.io/java.io.-file/walk.html). Если правильно сконфигурируете [`FileTreeWalk`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.io/-file-tree-walk/index.html), то очень легко получится реализовать логику по рекурсивному обходу. 
- [x] Есть еще такой замечательный extension в kotlin [`File::relativeTo`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.io/java.io.-file/relative-to.html). По-моему, Вам пригодится.
- [x] Ваша программа вообще ничего не делает, если ее запустить из консоли. На консоль вывод кто будет делать?)
- [x] Нет скриптов сборки/запуска. Я не могу нормально проверить, что Ваша программа действительно работает из командной строки.

**Comment by CrazyTosser** [comment]
Вроде все правки внес

**Comment by CrazyTosser** [comment]
И у меня какой-то странный баг. При тестировании через junit в результаты попадает "./", а когда я запускаю через скрипт - его нету

**Comment by JohnKhandygo** [comment]
Такое ощущение, что Вы даже не запускали свои тесты. Они вообще не работают. В следующий раз за такое буду баллы снимать.  
- [x] А можно обойтись без переменных среды? Как-то криво получается:  Вы в скрипте передаете в программу параметр, но не напрямую. Просто подставляйте pwd в качестве аргумента из скрипта, а в программе считайте, что аргумент обязателен. 
- [x] Что это за параметр `work`? Переменным надо давать "говорящие" названия. Это любого языка программирования касается.
- [x] Намекаю жирно: вместо того, что Вы делаете в `getPath` лучше воспользоваться методом [`File::relativeTo`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.io/java.io.-file/relative-to.html). А еще есть такой замечательный метод [`File::getName`](https://docs.oracle.com/javase/7/docs/api/java/io/File.html#getName()). 
- [x] Вместо `File::list` лучше использовать [`File::walk`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.io/java.io.-file/walk.html), надо только "настроить" полученный экземпляр [`FileTreeWalk`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.io/-file-tree-walk/index.html). Бонус в том, что `walk` метод перебирает файлы ленивым образом и так код будет выглядеть единообразным. 
- [x] Вывод на консоль сложно тестировать (собственно, Вы могли убедиться в этом сами). Для того, чтобы упростить себе жизнь стоит разработать отдельный метод/класс, который ищет и возвращает список папок, и его тестировать (без парсинга аргументов даже). В для вызова из консоли использовать другой метод, который будет дергать первый и "красиво" печатать список в консоль. 
- [x] Поправьте форматирование.

**Comment by CrazyTosser** [comment]
Тесты у меня рабочие. Только написаны они под линукс, а не под форточки. Могу прислать скрины подтверждение.
То что они не пашут на таковых я абсолютно случайно узнал сегодня утром. Мне тесты мудохать до совместимости с форточками или писать отдельные методы для никсов и для окон?

**Comment by JohnKhandygo** [comment]
> Только написаны они под линукс, а не под форточки.

Ваша программа работает только под линуксом? Если нет, то тесты должны подтеверждать ее корректность для любой ОС. В данном случае это не сложно. Проблема сейчас в line separator (`\n` для linux, `\r\n` для win). Если Вы перепишите тесты так, как указано в предпоследнем пункте замечаний, эта проблема исчезнет. Также может быть проблема с порядком следования файлов в выводе (для того, чтобы массивы/списки были равны, необходимо, чтобы элементы в вних были расположены в одинаковом порядке).

**Comment by CrazyTosser** [comment]
Вроде все поправил. Тесты перевел на Котлин

**Comment by JohnKhandygo** [comment]
Окей. Я только не понял, почему результат `Cli::run` сохраняется как состояние объекта.

**Comment by CrazyTosser** [comment]
Не хотел метод run открывать. Могу конечно и сделать его public. Но в 2 часа ночи это казалось хорошей идеей

**Comment by JohnKhandygo** [comment]
Вы можете сделать его  [`internal`](https://kotlinlang.org/docs/reference/visibility-modifiers.html#visibility-modifiers). Метод будет видел внутри проекта, но наружу не выставляется.

**Comment by CrazyTosser** [comment]
Хм... Об этом я как-то не подумал... Переделать или и так сойдёт?

**Comment by JohnKhandygo** [comment]
Сгодится. Главное, чтобы Вы чему-то научились в конце концов.
